settings:
  variables:
    entity_tablet: switch.galaxy_tab_a_screensaver
    entity_browser_mod: media_player.tablet
    translate_unknown: Unknown
    translate_idle: Idle
    translate_home: Home
    translate_not_home: Away
    translate_available: Available
    translate_no_updates: No updates
    translate_update_available: Update available
    translate_updates_available: Updates available
